apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: user-crud
build:
  artifacts:
    - image: wasil/user-crud-node
      context: app
deploy:
  kubectl:
    manifests:
      - kube/ingress.yaml
      - kube/deployment.yaml
      - kube/service.yaml
