apiVersion: 2
name: user-crud-chart
description: A Helm chart for Kubernetes

type: application

version: 0.2.2

appVersion: 0.2.2

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database